baseURL = "https://maryamalka.it.com/"
title = "Maryam Alka"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

enableRobotsTXT = true
enableEmoji = true

[pagination]
  pagerSize = 3

[params]
  author = "Maryam Alka"
  description = "AI Researcher | Applied Mathematician | Mathematical Oncologist"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  homeInfoParams = false

  [params.profileMode]
    enabled = true
    title = "Maryam Alka"
    subtitle = "AI Researcher · Applied Mathematician · Mathematical Oncologist"
    imageUrl = "1150.jpeg"
    imageTitle = "Maryam Alka"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:mxa1541@student.bham.ac.uk"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/maryam-alka-272102200"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/maryamalka85"

[menu]
  [[menu.main]]
    name = "More"
    url = "/posts/"
    weight = 1
