baseURL = "https://maryamalka.it.com/"
title = "Maryam Alka"
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"


enableRobotsTXT = true
enableEmoji = true

[pagination]
  pagerSize = 5

[params]
  author = "Maryam Alka"
  description = " AI Researcher | Applied Mathematician | Mathematical Oncologist"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  [params.profileMode]
    enabled = true
    title = "Maryam Alka"
    subtitle = "Applied Mathematician | AI Researcher | Mathematical Oncologist"
    imageUrl = "1150.jpeg"
    imageTitle = "Maryam Alka"


  [params.homeInfoParams]
    Title = "Hi, I'm Maryam 👋"
    Content = "Applied Mathematician and PhD researcher at the University of Birmingham, developing mathematical models of tumour growth under hypoxia and chemotherapy. I work at the intersection of mathematics, AI, and medicine."

  [[params.socialIcons]]
    name = "email"
    url = "mailto:mxa1541@student.bham.ac.uk"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/maryam-alka-272102200"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/maryamalka85"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Writing"
    url = "/posts/"
    weight = 2
